#!/bin/bash

source /usr/local/taiga/configure

cd /usr/local/taiga/taiga-back/

python manage.py collectstatic --noinput

while ! nc -z $POSTGRES_PORT_5432_TCP_ADDR $POSTGRES_PORT_5432_TCP_PORT; do
  echo "Waiting for Postgresql to be available..."
  sleep 1
done

python manage.py migrate --noinput

chown -R taiga /usr/local/taiga/media /usr/local/taiga/static /usr/local/taiga/logs

/usr/local/bin/circusd /usr/local/taiga/circus.ini
